language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.0
#  - jruby-19mode # JRuby in 1.9 mode

# fast-stemmer is a C extension, so it won't work with JRuby ...

# stemmer is the port that works for JRuby
before_install: (gem install fast-stemmer &); (gem install stemmer &); bundle install; sleep 10

notifications:
  recipients:
    - liebler.dominik@gmail.com
